# baseURL = "http://localhost:1313/"
baseURL = "https://my_Hugo_Blog.vercel.app"
title = "My Hugo Blog"
theme = "papermod"

[pagination]
  pagerSize = 5  # 替换旧的 paginate = 5

[params]
  description = "这是我的个人Hugo博客"
  author = "Jasion-han"